version: "3.4"
services:

  #deluge:
  #  container_name: deluge
  #  image: linuxserver/deluge:latest
  #  restart: unless-stopped
  #  # network_mode: host # run on the host network
  #  environment:
  #    - PUID=${PUID} # default user id, defined in .env
  #    - PGID=${PGID} # default group id, defined in .env
  #    - TZ=${TZ} # timezone, defined in .env
  #  volumes:
  #    - ${ROOT}/data/torrents:/data # downloads folder
  #    - /home/eric/dev-htpc/config/deluge:/config # config files
  #  ports:
  #    - 8112:8112
  #    - 6881:6881
  #    - 6881:6881/udp

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/eric/dev-htpc/config/jackett:/config
      - ${ROOT}/data:/data
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /home/eric/dev-htpc/config/sonarr:/config
      - /mnt/dev/data:/data

    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /home/eric/dev-htpc/config/radarr:/config
      - /mnt/dev/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    #network_mode: host
    volumes:
      - /home/eric/dev-htpc/config/plex/db:/config # plex database
      - /home/eric/dev-htpc/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414